apiVersion: v1
kind: Pod
metadata:
  name: news-portal
  labels:
    app: news-portal
spec:
  containers:
    - name: news-porta-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      env:
        - name: "IP_SISTEMA"
          value: "http://localhost:30001"